- .github/workflows/release.yml
> refactor: migrate Release Please action to new organization

- docs/best-practices.md
Document how we write input names, for future reference.
> docs: how to name inputs

- README.md
> docs: use Dependabot version updates

- CONTRIBUTING.md
> docs: roles and responsibilities

- docs/usage-examples.md
Update usage examples to be as minimal as possible (i.e. required inputs only).
> docs: update usage examples to be minimal

- .github/workflows/terraform.yml
> feat(terraform): disable top level GitHub token permissions

- .github/workflows/docker-acr.yml
- .github/workflows/docker.yml
> feat(docker): disable top level GitHub token permissions

- .github/workflows/azure-function.yml
- .github/workflows/azure-webapp.yml
- .github/workflows/commitlint.yml
- .github/workflows/docker-acr.yml
- .github/workflows/docker.yml
- .github/workflows/dotnet.yml
- .github/workflows/github-pages.yml
- .github/workflows/mkdocs-gh-pages.yml
- .github/workflows/mkdocs.yml
- .github/workflows/python.yml
- .github/workflows/semantic-release.yml
- .github/workflows/super-linter.yml
- .github/workflows/terraform.yml
> refactor: pin actions to commit SHA

- .github/workflows/docker-acr.yml
- .github/workflows/docker.yml
Replace environment variable `DOCKER_NO_BUILD_SUMMARY` with `DOCKER_BUILD_SUMMARY`.
> refactor(docker): replace deprecated environment variable

- .github/workflows/azure-function.yml
- .github/workflows/azure-webapp.yml
- .github/workflows/docker-acr.yml
- .github/workflows/github-pages.yml
- .github/workflows/release.yml
- .github/workflows/terraform.yml
Stop `YAML_PRETTIER` linter from complaining.
> style: format workflows with Prettier

- .github/workflows/azure-function.yml
> fix(azure-function): no artifact download

- .github/workflows/azure-webapp.yml
> fix(azure-webapp): no artifact download

- .github/workflows/dotnet.yml
Consistently write `.NET` instead of `Dotnet` in step names.
> style(dotnet): set consistent step names

- .github/workflows/terraform.yml
Makes logical sense to create summary of all steps at end of job.
> refactor(terraform): create summary at end of job

- .github/workflows/terraform.yml
Terraform related environments variables should be prefixed `TF_`.
> refactor(terraform): consistent envvar names

- .github/workflows/azure-function.yml
> fix(azure-function): unable to get access token from Azure CLI

- .github/workflows/azure-webapp.yml
> fix(azure-webapp): typo in `tar` command option

- .github/workflows/azure-webapp.yml
> fix(azure-webapp): unable to get access token from Azure CLI

- .github/workflows/release-please.yml
- .github/workflows/release.yml
Add workflow for automating GitHub releases using Release Please.
Refactor `release.yml` to call the reusable workflow.
> feat: add workflow `release-please.yml`

- .github/workflows/databricks-bundle.yml
Add workflow for deploying [Databricks Asset Bundles](https://learn.microsoft.com/en-us/azure/databricks/dev-tools/bundles/).
Implemented according to [official docs](https://learn.microsoft.com/nb-no/azure/databricks/dev-tools/bundles/ci-cd-bundles), however the use of environment variable `DATABRICKS_TOKEN` for authentication was replaced with the `azure/login` action, enabling secretless authentication.
> feat: add workflow `databricks-bundle.yml`

- .github/workflows/databricks-bundle.yml
Validate before deploy to fail faster.
> feat(databricks-bundle): validate before deploy
