equinor/ops-actions

- .github/workflows/docker-acr.yml
- .github/workflows/docker.yml
`docker/build-push-action` version 6 introduced generation of a job summary for build jobs, similar to our Terraform workflow.
Version 6 was merged in #498.
According to the action [README](https://github.com/docker/build-push-action/tree/v6/?tab=readme-ov-file#environment-variables), you can use environment variable `DOCKER_BUILD_NO_SUMMARY` to control the generation of this job summary. Explicitly set it to `false` to always generate job summary.
> feat(docker): generate job summary

- .github/workflows/azure-webapp.yml
> feat(azure-webapp): disable top level GitHub token permissions

- .github/workflows/azure-function.yml
> feat(azure-function): disable top level GitHub token permissions

- .github/workflows/dotnet.yml
> feat(dotnet): disable top level GitHub token permissions

- .github/workflows/github-pages.yml
Disable all permissions at the top level, then enable required permissions at job level instead. This is to ensure that we follow the principle of least privilege.
> feat(github-pages): disable top level GitHub token permissions

- .github/workflows/commitlint.yml
Disable all permissions at the top level, since no permissions are required. This is to ensure that we follow the principle of least privilege.
> feat(commitlint): disable top level GitHub token permissions

- .github/workflows/mkdocs-gh-pages.yml
- .github/workflows/mkdocs.yml
> feat(mkdocs): disable top level GitHub token permissions

- .github/workflows/super-linter.yml
Disable all permissions at the top level, then enable required permissions at job level instead. This is to ensure that we follow the principle of least privilege.
> feat(super-linter): disable top level GitHub token permissions

- .github/workflows/python.yml
Disable all permissions at the top level, then enable required permissions at job level instead. This is to ensure that we follow the principle of least privilege.
> feat(python): disable top level GitHub token permissions

- .github/workflows/terraform.yml
Only generate job summary for plans containing actual changes. Saves time as you won't have to check for empty plans.
> feat(terraform): skip job summary generation on empty plan

- .github/workflows/lint.yml
- .github/workflows/release.yml
Disable top level GitHub token permissions for non-reusable workflows used to automate tasks in this repository.
> ci: disable top level GitHub token permissions

- .github/workflows/super-linter.yml
Set all environment variables at the step scope rather than the job scope, since they're only required by a single step.
> refactor(super-linter): set environment variables at correct scope

- .github/workflows/commitlint.yml
Checkout repository, allowing configuration file (`commitlint.config.js`) to be read by the workflow.
> feat(super-linter): read configuration file

- .github/workflows/super-linter.yml
Checkov and JSCPD linters ignore the `FILTER_REGEX_EXCLUDE`, `FILTER_REGEX_INCLUDE` and `VALIDATE_ALL_CODEBASE` environment variables. Explicitly disable these linters to prevent them from being run when they should not.
> fix(super-linter): disable Checkov and JSCPD linters

- .github/workflows/lint.yml
Set required permissions for Super-linter job to run successfully.
> ci: set required permissions for jobs

- scripts/oidc/oidc.sh
jq option `-j` implies `-r` while also excluding line endings that would be added by jq (not including explicit line endings in the config file).
> chore: exclude line endings when reading OIDC config file

- .editorconfig
- scripts/oidc/oidc.sh
Trying to prettify the OIDC script a bit to make it slightly more pleasant to work in and with.
- Use uppercase for environment variables and constants.
- Use lowercase for local variables.
- Set environment variables and constants to read-only as soon as possible.
- Only wrap variable references with `{}` if required.
- Don't exceed 80 character line limit.
> chore: prettify OIDC script

- scripts/oidc/oidc.sh
- scripts/terraform-backend/terraform-backend.sh
Trying to prettify the Terraform backend script a bit to make it slightly more pleasant to work in and with.
- Use uppercase for environment variables and constants.
- Use lowercase for local variables.
- Set environment variables and constants to read-only as soon as possible.
- Only wrap variable references with `{}` if required.
- Add functions for printing error and info messages.
- Don't exceed 80 character line limit.
Similar to #571. That PR should be merged first so that this PR can get the benefits of the added `.editorconfig` file.
> chore: prettify Terraform backend script

- .github/workflows/terraform.yml
- Remove use of environment variable `TF_CLI_ARGS_init` to add optional arguments to `terraform init` command calls. This was useful back when we used to run `terraform init` twice in the workflow (since the environment variable would add the optional args to both command calls), however we no longer do that. Prefer the same logic for optional arguments used in step `Terraform Plan`, for consistency's sake. 
- Remove a newline in step `Terraform Plan`, effectively grouping related commands.
> refactor(terraform): common logic for passing optional args

- .github/workflows/terraform.yml
Instead of removing formatting check completely, simply configure the workflow to continue even when formatting check throws error. Consider it an alternative fix to #568.
> fix(terraform): formatting errors prevent job from running

- scripts/terraform-backend/terraform-backend.sh
Prevents script from reverting firewall default action or IP rules when targeting an existing Storage account.
> chore: only update security features for existing Terraform backends

- .github/workflows/terraform.yml
- Add new input `run_terraform_apply`.
- If value is `true`, the `Terraform Apply` job will run after generating a plan.
- If value is `false`, the `Terraform Apply` job will **not** run after generating a plan.
- Default value is `true`, to keep the default behavior of the workflow the same as before.
This allows users to run `terraform apply` job based on a condition.
For example, run `terraform plan` on PR to branch `main`, then run `terraform plan` and `terraform apply` on push to branch `main`:
```yaml
on:
pull_request:
branches:
- main
push:
branches:
- main
jobs:
example:
uses: equinor/ops-actions/.github/workflows/terraform.yml@feat/terraform/add-option-to-run-apply-on-condition
with:
environment: dev
run_terraform_apply: ${{ github.event_name == 'push' && github.ref == …
```
> feat(terraform): add option to run Apply on condition

- .github/workflows/dotnet.yml
Workflow fails due to no artifact is being generated. The workflow expects `$ARTIFACT_NAME` but its never speciefied, causing the path to end in a `.tar` file, which is classified as a hidden file.
> fix(dotnet): no artifact uploaded

- .github/workflows/terraform.yml
When enabling the plugin cache, Terraform will create symbolic links in the current working directory to the plugin cache directory. As a result, the plugin cache directory must be included in the artifact to be download by the `Terraform Apply` job.
> fix(terraform): include plugins downloaded from cache in artifact

- .github/workflows/terraform.yml
`TF_PLUGIN_CACHE_DIR` should be an absolute path to ensure consistent behavior across actions and inline scripts. Currently the `actions/cache` action looks for plugins to cache at the incorrect path, resulting in an empty cache.
> fix(terraform): no plugins uploaded to cache

- scripts/oidc/README.md
- scripts/oidc/oidc.sh
Allow easier targeting of specific GitHub repo and Azure subscription.
> chore: specify OIDC source repo and target subscription

- docs/best-practices.md
- Format using `prettier`.
- Fix linter problems detected by `textlint`:
- "kebab case" to "kebab-case"
- "snake case" to "snake_case"
- "file names" to "filenames"
> docs: fix linter and formatting problems

- .github/workflows/terraform.yml
No need to install Terraform wrapper script when its functionality is not used.
This is already done in the `terraform-plan` job.
> refactor(terraform): explicitly disable wrapper script

- .github/workflows/terraform.yml
Plan job will either restore an existing cache or save cache. Thus, in the apply job, we can expect there to always be cache available. If not, something is wrong.
> fix(terraform): apply job should fail if unable to restore cache

- .github/workflows/terraform.yml
Cache functionality currently breaks the workflow if the dependency lock file (`.terraform.lock.hcl`) has not been commited.
While it's _recommended_ to commit the lock file, it's not _required_. It should be okay to skip caching plugins if lock file has not been commited.
Check if lock file exists:
- If yes, enable plugin cache.
- If no, don't enable plugin cache and skip all cache related steps.
(see results in comments)
> fix(terraform): apply job fails if lock file has not been commited

- .github/workflows/docker-acr.yml
- .github/workflows/docker.yml
- .github/workflows/terraform.yml
Job outputs often reference the steps in the job, so it makes more sense to place the outputs after the steps they reference.
> refactor: declare job outputs and end of job

- .github/workflows/dotnet.yml
npm allows you to install packages for ASP.NET Core applications.
Some ASP.NET Core applications might require a specific version of npm and Node.js to be installed. If yes, this workflow should install the specified versions (already implemented). Else, this workflow should skip the setup of npm (already implemented) and Node.js (implemented in this commit).
> fix(dotnet): skip Node.js setup if no version specified

- .github/workflows/terraform.yml
The `Terraform Apply` job does not restore cache if the `Terraform Plan` job does not save cache. This causes an error in scenarios where cache already exists, and it'll only be restored in the `Terraform Plan` job but not the `Terraform Apply` job.
> fix(terraform): cache not restored in Apply job

- .github/workflows/terraform.yml
Currently, the `Enable Terraform plugin cache` step does not output anything to the log when the plugin cache is enabled.
Add an `echo` command to output to log that the plugin cache was enabled.
> fix(terraform): no log output when plugin cache enabled

- .github/workflows/terraform.yml
Currently, if the Terraform workflow is triggered by Dependabot, both the `Terraform Plan` and `Terraform Apply` jobs are skipped, meaning the workflow does nothing 🤷 With the changes in this PR, the workflow should run until at least the `Terraform Validate` step to catch obvious errors.
If triggered by Dependabot, it's important that the Terraform backend is _not_ initialized when running `terraform init`, since that requires authentication to Azure, which Dependabot can't do.
> feat(terraform): validate configuration if triggered by Dependabot

- .github/workflows/dotnet.yml
.NET related environment variables should be prefixed `DOTNET_`.
> refactor(dotnet): consistent envvar names

- .github/workflows/terraform.yml
Long options are more self-documenting than short options.
> style(terraform): use long options for commands

- .github/workflows/azure-function.yml
- .github/workflows/azure-webapp.yml
- .github/workflows/docker-acr.yml
- .github/workflows/terraform.yml
* Change `Azure AD` to `Microsoft Entra`.
* Clarify that these secrets are for configuring authentication to Azure.
Release-As: 9.13.3
> refactor: update descriptions for Azure secrets

- .github/workflows/azure-function.yml
- .github/workflows/azure-webapp.yml
- .github/workflows/docker-acr.yml
Some commands may output secrets. Output can be explicitly enabled for commands that require it by using the `--output` argument.
> feat: disable Azure CLI output by default

- .github/workflows/azure-function.yml
- .github/workflows/azure-webapp.yml
- .github/workflows/docker-acr.yml
- docs/best-practices.md
Remove duplicate comments in workflows, and add new item to best practices instead.
> docs: disable Azure CLI output by default

- .github/workflows/databricks-repos.yml
Simplify the use of the `databricks-repos.yml` workflow by setting a default value for input `repo_path` that corresponds to the GitHub repository that is being pulled into Databricks.
> feat(databricks-repos): set default repo path

- .github/workflows/super-linter.yml
The Ruff linter is faster than, has feature parity with, and serves as a drop-in replacement for both Flake8 and isort.
> feat(super-linter): prefer Ruff over Flake8 and isort

- .github/workflows/super-linter.yml
Disable creation of status checks per linter. Instead, create a single status check for the entire linter workflow job, then create a job summary that lists all linters that were run.
This is to prevent an overly long list of status checks for pull requests that include many different languages to be linted.
> feat(super-linter): create job summary instead of status checks

- .github/workflows/databricks-bundle.yml
- .github/workflows/databricks-repos.yml
Repos and bundles are two completely different features in Databricks that do not conflict with each other.
A job that updates a repo should not block a job that wants to deploy a bundle. Each workflow should target a separate concurrency queue.
> fix: `databricks-repos.yml` and `databricks-bundle.yml` use same concurrency queue

- .github/workflows/terraform.yml
Concurrency group should not be determined solely on the working directory, as it's possible to target the same working directory while using a partial backend configuration to target different Terraform state files.
Fixes #717
> fix(terraform): jobs that target different state files run in same concurrency group

- .github/workflows/terraform.yml
- Add a new optional secret `GRAFANA_AUTH`, where you can pass a service account token to authenticate the Grafana provider. The description intentially starts with `A` instead of `The` (like the existing required secrets) to highlight that this is an *optional* secret.
- Pass this secret to a new workflow-level environment variable `GRAFANA_AUTH`, which will be used to authenticate the Grafana provider, as described in the [official Grafana provider documentation](https://registry.terraform.io/providers/grafana/grafana/3.25.6/docs).
> feat(terraform): authenticate Grafana provider

- docs/best-practices.md
Added a note after running into this bug: https://github.com/Azure/azure-cli/issues/31591
Discovered that Azure CLI had been updated in the ubuntu-24-04 image to fix the bug.
> chore: add notes on runner image versions

- .github/workflows/release-please.yml
Upgrades `googleapis/release-please-action` to 4.3.0 to address [googleapis/release-please-action#867](https://github.com/googleapis/release-please-action/issues/867)
> chore: upgrade release-please workflow to 4.3.0

- .github/workflows/commitlint.yml
- .github/workflows/databricks-bundle.yml
- .github/workflows/docker-acr.yml
- .github/workflows/docker.yml
- .github/workflows/dotnet.yml
- .github/workflows/mkdocs-gh-pages.yml
- .github/workflows/mkdocs.yml
- .github/workflows/python.yml
- .github/workflows/semantic-release.yml
- .github/workflows/super-linter.yml
- .github/workflows/terraform.yml
- docs/best-practices.md
If the value of input `persist-credentials` is set to `true`, the `actions/checkout` action will authenticate Git. The auth token is persisted in the local Git config.
If a workflow does not explicitly need Git to be authenticated, persisting the token poses a potential security risk. By setting the value of this input to `false`, we opt-out of this behavior.
> feat: disable Git credential persistance

- .github/workflows/docker-acr.yml
- .github/workflows/docker.yml
In `docker-acr.yml`, pin `docker/setup-buildx-action` action to commit SHA.
In `docker.yml`, pin `docker/setup-buildx-action` action to same commit SHA as in `docker-acr.yml`. Previous commit SHA is not associated with a release, which seems to have broken Release-Please updates for this specific action.
> fix(docker): pin `docker/setup-buildx-action` action to commit SHA

- .github/workflows/docker-acr.yml
- .github/workflows/docker.yml
According to the `zizmor` linter, the `context` input for the `docker/build-push-action` action accepts arbitrary code, and could be used to inject malicious code. To remediate this vulnerability, replace the use of the `context` input in the `docker.yml` and `docker-acr.yml` workflows with the `file` input.
After making this change, running `zizmor` reports no known vulnerabilities for the `docker.yml` and `docker-acr.yml` workflows:
```console
$ zizmor docker.yml
INFO zizmor::registry: skipping impostor-commit: can't run without a GitHub API token
INFO zizmor::registry: skipping ref-confusion: can't run without a GitHub API token
INFO zizmor::registry: skipping known-vulnerable-actions: can't run without a GitHub API token
INFO zizmor::registry: skipping forbidden-uses: audit not …
```
> fix(docker): prevent code injection via template expression

- .github/workflows/release-please.yml
Breaks monorepo releases by default, i.e. repos that use a `release-please-config.json` file to configure multiple packages to be released in a single repo.
Not a breaking change since Release Please assumes a simple release by default.
> fix(release-please): remove default release type
